#!/usr/bin/env python3
"""Pipeline helper to convert Premiere XML to OTIO and render an MP4."""

from __future__ import annotations

import argparse
from pathlib import Path

from ffmpeg_video_creator import render_mp4_from_xml
from xml_to_otio_converter import (
    OUTPUT_DIR,
    convert_xml_to_otio,
    find_latest_pipeline_xml,
    find_xml_in_input,
)


def choose_xml_path(cli_value: Path | None) -> Path:
    if cli_value:
        return cli_value
    candidate = find_xml_in_input()
    if candidate:
        return candidate
    candidate = find_latest_pipeline_xml()
    if candidate:
        return candidate
    raise FileNotFoundError("No Premiere XML provided and none found in default locations.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a reference MP4 from the latest Groq pipeline XML. "
            "If --xml is omitted, the script looks inside ffmpeger_otio_video_maker/input, "
            "then xml_insertor/output (final Groq export), and finally xml_editor_after_comparser/output."
        )
    )
    parser.add_argument("--xml", type=Path, help="Optional path to a specific Premiere XML file.")
    parser.add_argument("--mp4", type=Path, help="Destination path for the rendered MP4.")
    parser.add_argument(
        "--track-index",
        type=int,
        help="Render a specific video track (defaults to the first track).",
    )
    parser.add_argument(
        "--keep-otio",
        action="store_true",
        help="Keep the generated OTIO file instead of deleting it after rendering.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    xml_path = choose_xml_path(args.xml)
    # Reuse the OTIO if already generated by an earlier pipeline step.
    otio_path = OUTPUT_DIR / f"{xml_path.stem}.otio"
    if not otio_path.exists():
        otio_path = convert_xml_to_otio(xml_path)
    mp4_path = render_mp4_from_xml(xml_path, args.mp4, args.track_index)
    if not args.keep_otio and otio_path.exists():
        try:
            otio_path.unlink()
        except OSError:
            pass
    print(f"MP4 written to {mp4_path}")


if __name__ == "__main__":
    main()
